// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:eaee8b96-b627-461a-9418-8fa417bb818c",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_HlfBbQNWd",
    "aws_user_pools_web_client_id": "323s63ie53pscq31uqrngofmss"
};


export default awsmobile;
